services:
  icfpc_test_postgres:
    image: pgautoupgrade/pgautoupgrade:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - default
      - redash_default

networks:
  redash_default:
    external: true