version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5050:5432"
    networks:
      - icfpc
    environment:
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'postgres:/var/lib/postgresql/data'

  #  pgadmin:
  #    image: dpage/pgadmin4:latest
  #    depends_on:
  #      - postgres
  #    restart: always
  #    networks:
  #      - icfpc
  #    ports:
  #      - "5055:80"
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: 'user@test.com'
  #      PGADMIN_DEFAULT_PASSWORD: 'ghjdthrf'
  #    volumes:
  #      - 'pgadmin:/var/lib/pgadmin'

  teamcity:
    image: jetbrains/teamcity-server
    depends_on:
      - postgres
    restart: always
    ports:
      - "8111:8111"
    volumes:
      - 'teamcity:/data/teamcity_server/datadir'

networks:
  icfpc:
    driver: bridge

volumes:
  postgres:
  teamcity:
#  pgadmin: