spring:
  application:
    name: icfpc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/icfpc'
    username: 'icfpc'
    password: 'icfpc'
    hikari:
      maximum-pool-size: 2
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update