services:
  server:
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@icfpc_postgres/postgres?sslmode=disable
    restart: always
    build:
      context: ../icfpc
      dockerfile: Dockerfile
    ports:
      - "${ICFPC_SERVER_PORT}:8080"
    depends_on:
      - icfpc_postgres

  icfpc_postgres:
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    image: pgautoupgrade/pgautoupgrade:latest
    volumes:
      - ${ICFPC_BASE_PATH}/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default
      - redash_default

networks:
  redash_default:
    external: true
